version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_market
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: never-put-passwords-in-files
      MYSQL_DATABASE: personnel
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

volumes:
  mysql_data:
